### ISSUE TITLE
"Install Steam" button remains visible on help.steampowered.com

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#167]
### Describe the bug

With the option to hide the "Install Steam" button enabled, the button remains visible on https://help.steampowered.com/.

### Browser name and version

Firefox 124.0

**Comment by xPaw** [comment]
That's fine, I don't think it needs to be hidden on the help pages. It also doesn't get hidden on login page (and some others) because the script is intentionally not run on these pages: 
https://github.com/SteamDatabase/BrowserExtension/blob/1b05ecdea6447099e0d3fc155873502b4d00395a/manifest.json#L107-L123
