### ISSUE TITLE
Ability to append or modify "SteamDB" when translating.

### ISSUE THREAD

**Issue by thisiselias** [SteamDatabase/BrowserExtension#174]
### Is your feature request related to a problem? Please describe.

When translating it is not possible to append or add anything to "SteamDB". I get why this is done, but it causes issues with languages that use possessive case to refer to ownership, and results in unnecessary or overcomplicated rephrasing of translations.

I've attached a screenshot that shows an example of this happening.
![image](https://github.com/SteamDatabase/BrowserExtension/assets/159950724/98844ad6-e520-4070-8792-293a6b826e3a)

### Describe the solution you'd like

Allowing modifications of the term "SteamDB". This will surely lead to time spent checking that "SteamDB" has been spelt correctly, but this sounds like a fair tradeoff in the pursuit of better quality translations.

### Describe alternatives you've considered

If not, then rephrasing will be used. This will impair translations.

**Comment by Tobost06** [comment]
This is not an issue with SteamDB, but how Crowdin works. It's due to the "SteamDB" term being set to Non-translatable.
![image](https://github.com/SteamDatabase/BrowserExtension/assets/114383977/71aa4651-dc48-4f32-85df-e9faadddc67d)
It's as simple as checking the box and making it "Translatable", though that should be decided upon by @xPaw.

**Comment by xPaw** [comment]
I've enabled translatable, but please don't translate it.
